### ISSUE TITLE
PROBLEMA IN INSTALL

### ISSUE THREAD

**Issue by Armando1514** [spagnuolocarmine/ubuntu-openmpi-openmp#1]
Ricevo un comando non trovato alla linea 
sudo usermod -aG sudo pcpc
e inoltre alla linea sudo -u pcpc sudo ldconfig
il terminale si blocca, e una volta cliccato invio mi chiede una password di cui non sono a conoscneza. ANY SOLUTIONS?

**Comment by MatDau** [comment]
Ciao, mi sembra davvero particolare che tu abbia un problema di comando non trovato alla linea "sudo usermod -aG sudo pcpc" dato che sono comandi base di Linux, mi puoi dare maggiorni informazioni riguardo la macchina su cui stai eseguendo lo script oppure allegare qualcosa che possa essermi di aiuto. 
Per il problema alla linea "sudo -u pcpc sudo ldconfig" è dovuto al problema della linea precedente perché non mettendoti nei sudo user non puoi utilizzare la tua password
