### ISSUE TITLE
Sono riuscito a creare un cluster ma il test di un programma con MPI non viene eseguito

### ISSUE THREAD

**Issue by emaiannone** [spagnuolocarmine/ubuntu-openmpi-openmp#2]
Ho creato un cluster di prova con 4 macchine. Su ciascuna ho eseguito passo passo il processo di setup, come riportato su GitHub. Quindi ho generato le chiavi ssh sul nodo master; le ho inserite nello script install.sh; ho copiato con scp lo script su tutti i nodi; ho eseguito lo script su ciascun nodo.
Andando sul nodo master, all'utente pcpc, ho lanciato: "mpicc -fopenmp test.c -o test.out", e viene creato il file test.out correttamente. Tuttavia al lancio con: "mpirun -np 2 ./test.out" ottengo il seguente errore:
"There are not enough slots available in the system to satisfy the 2 slots
that were requested by the application:
  ./test.out
Either request fewer slots for your application, or make more slots available
for use."

Deduco che il master non riesca a connettersi con i nodi slave. C'è un modo per essere sicuri che il master "veda" gli slave?

**Comment by spagnuolocarmine** [comment]
Salve deve copiare il file compilato o compilare su ogni nodo slave. 

Inoltre deve essere sicuro che il file da eseguire si trova nello stesso path su tutti i nodi, in particolare partendo dalla /home/pcpc

**Comment by FranCali** [comment]
Ho lo stesso problema di @emaiannone , quando vado ad eseguire su un nodo il programma con 'mpirun -np 2 ./test' si ottiene l'errore:
'There are not enough slots available in the system to satisfy the 2 slots
that were requested by the application:
  ./test

Either request fewer slots for your application, or make more slots available
for use.'

Ho creato e compilato il file su ogni nodo slave e nello stesso percorso /home/pcpc
Non vorrei dire una sciocchezza ma puo' darsi che non riesce a trovare gli slot nel sistema perche' cerca processori all'interno della singola macchina ma le nostre istanze t2.micro hanno una sola vCPU.

**Comment by spagnuolocarmine** [comment]
Purtroppo è una nuova feature/bug della ultima versione di OpenMPI.
Come segnalato in quest thread di [stackoverflow](https://stackoverflow.com/questions/35704637/mpirun-not-enough-slots-available).

Per risolvere il problema dovete creare nel medesimo path dove avete compilato il vostro programma, un file chiamato machinefile, che contiene per ogni riga i nodi dove volete eseguire il programma.

```
localhost slots=1
172.16.3.1 slots=1
..
..
```

Inoltre bisogna utilizzare gli IP interni di AWS e specificare il numero di slots, che corrisponde al numero di VCPU, nel vostro caso di istanze t2.micro 1 slot.

Per avviare MPI specificando il hosts file:
```
mpirun --hostfile hostfile -np 2 a.out

```

Il numero di processi MPI (-np) deve essere uguale alla somma degli slot specificati nell'host file.

**Comment by FranCali** [comment]
Funziona grazie, avevo un altro problema di connessione TCP negata ma dovevo aggiungere la regola di inbound nel security group per TCP Anywhere. Grazie.
